/** Post-run pipeline: commit, push, PR, card move */

import { logger } from './logger';
import type { RepoManager } from './repoManager';
import type { GraphQLClient } from './graphql';
import type { IssueContext, AgentResult } from './claudeHarness.types';

/**
 * Execute post-run pipeline after successful agent completion.
 */
export async function runPostRunPipeline(
  ctx: IssueContext,
  worktreePath: string,
  key: string,
  repoManager: RepoManager,
  graphql: GraphQLClient
): Promise<AgentResult> {
  logger.info(`[Pipeline.runPostRunPipeline] Starting for ${key}`);

  const hasChanges = await repoManager.hasStagedChanges(worktreePath);
  if (!hasChanges) {
    logger.warn(`[Pipeline.runPostRunPipeline] No staged changes in ${worktreePath}`);
    return { success: true, issueNumber: ctx.issueNumber, reason: 'No changes staged' };
  }

  const commitMessage = `ai-os: ${ctx.title} (#${ctx.issueNumber})`;
  const sanitizedMessage = commitMessage.replace(/\n/g, ' ').replace(/"/g, '\\"');
  const commitResult = await repoManager.commitWorktree(worktreePath, sanitizedMessage);
  if (!commitResult.success) {
    logger.error(`[Pipeline.runPostRunPipeline] Commit failed: ${commitResult.error}`);
    return {
      success: false,
      issueNumber: ctx.issueNumber,
      reason: 'COMMIT_FAILED',
      error: commitResult.error,
    };
  }
  logger.info(`[Pipeline.runPostRunPipeline] Commit succeeded for ${key}`);

  const branchName = repoManager.getBranchName(ctx.repo, ctx.issueNumber, ctx.title);
  const pushResult = await repoManager.pushWorktree(worktreePath, branchName);
  if (!pushResult.success) {
    logger.error(`[Pipeline.runPostRunPipeline] Push failed: ${pushResult.error}`);
    return {
      success: false,
      issueNumber: ctx.issueNumber,
      reason: 'PUSH_FAILED',
      error: pushResult.error,
    };
  }
  logger.info(`[Pipeline.runPostRunPipeline] Push succeeded for ${key}`);

  try {
    const repoId = await getRepositoryNodeId(graphql, ctx.owner, ctx.repo);
    const defaultBranch = await getDefaultBranch(repoManager, ctx.owner, ctx.repo);
    const prResult = await graphql.createPullRequest(
      repoId,
      branchName,
      defaultBranch,
      commitMessage,
      `Auto-generated by AI OS for issue #${ctx.issueNumber}\n\n${ctx.body ?? ''}`
    );
    if (prResult.success && prResult.prUrl) {
      logger.info(`[Pipeline.runPostRunPipeline] PR created: ${prResult.prUrl}`);
      return { success: true, issueNumber: ctx.issueNumber, reason: 'Complete', prUrl: prResult.prUrl };
    } else {
      logger.warn(`[Pipeline.runPostRunPipeline] PR creation failed (best-effort): ${prResult.error}`);
    }
  } catch (error) {
    logger.warn(`[Pipeline.runPostRunPipeline] PR creation error (best-effort): ${(error as Error).message}`);
  }

  return { success: true, issueNumber: ctx.issueNumber, reason: 'Complete' };
}

async function getDefaultBranch(repoManager: RepoManager, owner: string, repo: string): Promise<string> {
  logger.info(`[Pipeline.getDefaultBranch] owner=${owner} repo=${repo}`);
  try {
    const branch = await repoManager.detectDefaultBranch(owner, repo);
    logger.info(`[Pipeline.getDefaultBranch] Result: ${branch}`);
    return branch;
  } catch (error) {
    logger.warn(`[Pipeline.getDefaultBranch] Error: ${(error as Error).message}. Defaulting to main`);
    return 'main';
  }
}

async function getRepositoryNodeId(graphql: GraphQLClient, owner: string, repo: string): Promise<string> {
  logger.info(`[Pipeline.getRepositoryNodeId] owner=${owner} repo=${repo}`);
  try {
    const result = await graphql.execute<{ repository: { id: string } }>(
      'query GetRepoId($owner: String!, $name: String!) { repository(owner: $owner, name: $name) { id } }',
      { owner, name: repo }
    );
    const id = result.repository?.id ?? '';
    logger.info(`[Pipeline.getRepositoryNodeId] Result: ${id}`);
    return id;
  } catch (error) {
    logger.error(`[Pipeline.getRepositoryNodeId] Error: ${(error as Error).message}`);
    throw error;
  }
}
